BinaryTreeApplication/Models/Node.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BinaryTreeApplication.Models
{
    public class Node
    {
        public int? value { get; set; }
        public Node left { get; set; }
        public Node right { get; set; }

        public Node(int? data)
        {
            value = data;
            right = null;
            left = null;
        }

    }
}

BinaryTreeApplication/Controllers/NodesController.cs
using BinaryTreeApplication.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BinaryTreeApplication.Controllers
{
    public class NodesController : Controller
    {        
        private Node root; 
        List<int?> values = new List<int?>();
        
        public ActionResult BinaryTree()
        { 
            return View();  
        }

        [HttpPost]
        public ActionResult BinaryTree(string action)  
        {
            int value;               
            int nodeSearch1;
            int nodeSearch2;
            Node parent;

            switch (action)
            {
                case "Insertar":

                    var pru = Request.Form["data"];
                    if (pru == "")
                    {
                        ViewBag.Value = "Debe ingresar un valor";
                        break;
                    }                        

                    value = Convert.ToInt32(Request.Form["data"]);                    

                    if (Session["data"] != null)
                        values = (List<int?>)Session["data"];
                    
                    values.Add(value);
                                        
                    Session["data"] = values;

                    ViewBag.Value = value;
                    break;

                case "Buscar":
                    var pru1 = Request.Form["nodeSearch1"]; 
                    var pru2 = Request.Form["nodeSearch2"];
                    if (pru1 == "" || pru2 == "")
                    {
                        ViewBag.Parent = "Debe ingresar un valor";
                        break;
                    }

                    values = (List<int?>)Session["data"];

                    foreach (var n in values)
                    {
                        root = Insert(root, n);
                    }                    
                                       
                    nodeSearch1 = Convert.ToInt32(Request.Form["nodeSearch1"]);
                    nodeSearch2 = Convert.ToInt32(Request.Form["nodeSearch2"]);

                    parent = Ancestor(root, nodeSearch1, nodeSearch2);                     

                    if (parent != null) { ViewBag.Parent = parent.value; }                        
                    else { ViewBag.Parent = "El ancestro no existe"; }
                    break;
            }          

                                          
            return View("BinaryTree", root);            

        }

        public Node Insert(Node current, int? data)  
        { 
            if (current == null)
            {
                return new Node(data);           
            }

            if (data < current.value)
            {
                current.left = Insert(current.left, data);
            }
            else
            {
                current.right = Insert(current.right, data);
            }

            return current;
        }                

        public Node Ancestor(Node node, int n1, int n2)
        {
            if (node == null)
            {
                return null;  
            }
            
            if (node.value > n1 && node.value > n2)
            {
                return Ancestor(node.left, n1, n2);
            }
            
            if (node.value < n1 && node.value < n2)
            {
                return Ancestor(node.right, n1, n2);
            }

            return node;  
        }


    }
}

BinaryTreeApplication/Views/Nodes/BinaryTree.cshtml
@model BinaryTreeApplication.Models.Node

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
</head>
<body>
    @using (Html.BeginForm("BinaryTree", "Nodes", FormMethod.Post))
    {
        <div id="generic_price_table">
            <section>
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <!--PRICE HEADING START-->
                            <div class="price-heading clearfix">
                                <h2>Árbol Binario</h2>
                            </div>
                            <!--//PRICE HEADING END-->
                        </div>
                    </div>
                </div>
                <div class="container" align="center">
                    <hr width="20%" />
                    <div class="head_bg"></div>
                    <div class="head">
                        <span>Creando el árbol</span>
                    </div>
                    <hr width="20%" />
                    <br />

                    <div class="head_bg"></div>
                    <div class="head">
                        <span>Ingrese un valor numérico:</span>
                    </div>
                    <br />
                    <div>
                        <input class="inputstyle" type="number" name="data" value="">
                    </div>
                    <br />
                    <div>
                        <div>
                            <input class="buttonstyle" type="submit" name="action" value="Insertar" />
                        </div>
                    </div>
                    <br />                    

                    <div class="head_bg"></div>
                    <div class="head">
                        <span>Se ha ingresado:</span>
                    </div>
                    <div>
                        <span>
                            <span>@ViewBag.Value</span>
                        </span>
                    </div>
                    <br />

                    <hr width="20%" />
                    <div class="head_bg"></div>
                    <div class="head">
                        <span>Buscando el ancestro</span>
                    </div>
                    <hr width="20%" />
                    <br />
                    <div class="head_bg"></div>
                    <div class="head">
                        <span>Ingrese los nodos:</span>
                    </div>
                    <br />
                    <div>
                        <input class="inputstyle" type="number" name="nodeSearch1" value="">
                    </div>
                    <br />
                    <div>
                        <input class="inputstyle" type="number" name="nodeSearch2" value="">
                    </div>
                    <br />
                    <div>
                        <div>
                            <input class="buttonstyle" type="submit" name="action" value="Buscar" />
                        </div>
                    </div>
                    <br />
                    <div class="head_bg"></div>
                    <div class="head">
                        <span>Ancestro encontrado:</span>
                    </div>
                    <div class="generic_price_tag clearfix">
                        <span class="price">
                            <span class="cent">@ViewBag.Parent</span>
                        </span>
                    </div>
                </div>
                
            </section> 
        </div>
        
    }
</body>
</html>